### ISSUE TITLE
Alternative Icons

### ISSUE THREAD

**Issue by u0398** [mikedigriz/Syncthing-for-PocketBook#5]
I made a Syncthing icon in the Pocketbook style that might be worth including.

[syncthing-pocketbook-style.zip](https://github.com/user-attachments/files/16038514/syncthing-pocketbook-style.zip)

**Comment by mikedigriz** [comment]
Thank you! Nice and clean icons.

**Comment by u0398** [comment]
I have not my updated PocketBook in a while, but I will, and see if I can't help with the icons!
